### ISSUE TITLE
用户名密码随便输都登录成功获取token

### ISSUE THREAD

**Issue by fei-shen-null** [khlipeng/lumen-api-jwt#1]
```
    'guards' => [
        'api' => [
            'driver' => 'api',
            'provider' => 'users',
            'identifier' => 'username',
            'password' => 'password',
        ],
    ],
```
```
    protected function getCredentials(Request $request)
    {
        return $request->only('username', 'password');
    }
```
请求{"username":"错误的账号","password":"错误的密码"}
返回
`{"success":{"message":"token_generated","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjI1NSwiaXNzIjoiaHR0cDpcL1wvd2VpeGluLmRldlwvYXV0aFwvbG9naW4iLCJpYXQiOjE0NjY2NTEwMzYsImV4cCI6MTQ2NjY1NDYzNiwibmJmIjoxNDY2NjUxMDM2LCJqdGkiOiJiZTkyNDFhYzlhMjRjNDY3ZDNiNTI5YWFmODVmOTZlNCJ9.zXV0DLhGUjdhOhHiKzgqWE5g2z8VI5yMCVRZTSzza6I"}}`
怎么回事啊

$credentials的值没问题
打印出sql显示为select * from `im_users` limit 1

**Comment by khlipeng** [comment]
@fei-shen-null 这个问题我在搭建这个的时候就发现了，暂时就没有去完善它。

**Comment by khlipeng** [comment]
@fei-shen-null 你好，问题已经修复。
