### ISSUE TITLE
Not getting the right user from token after logging in

### ISSUE THREAD

**Issue by jonasvanderhaegen** [khlipeng/lumen-api-jwt#2]
Hello Khlipeng

Thank you for making it work so far, I only have an issue with multiple users. When I log in with for example user 4 or user 5 it seems to go wrong here : JWTAuth::attempt($credentials). It does get me logged in but with user 1 instead of user 4 or 5. When I get information from the token it always gives me user 1's information.

Can you test and correct this with multiple accounts please? 
Thanks in advance!

**Comment by khlipeng** [comment]
@jonasvanderhaegen  In Lumen's use, there are some problems, use or reference https://github.com/khlipeng/laravel_api

**Comment by khlipeng** [comment]
@jonasvanderhaegen Hello, the problem has been fixed

**Comment by jonasvanderhaegen** [comment]
@khlipeng Nice man, thank you very much! I'll try again later today to confirm.
